// Generated by scripts/generate-third-party-notices.sh from THIRD-PARTY-NOTICES.txt.
// Do not edit by hand; run the script again instead.

enum ThirdPartyNotices {
    static let text = #"""
THIRD-PARTY NOTICES

Icontuck does not bundle any third-party libraries. It is built only from its
own Swift sources against Apple's system frameworks (AppKit, SwiftUI and
ServiceManagement), which are part of macOS and are not redistributed with the
app, so there are no third-party licenses to reproduce here.

Icontuck itself is released under the MIT License; see LICENSE in
https://github.com/cyberneura/icontuck.

Generated by scripts/generate-third-party-notices.sh; do not edit by hand.
"""#
}
