#!/usr/bin/env bash
# Writes THIRD-PARTY-NOTICES.txt, the licenses of every third-party library that
# ships inside Icontuck.app, and Icontuck/ThirdPartyNotices.swift, which embeds
# the same text in the binary for the "Third-Party Licenses…" menu item.
#
#   ./scripts/generate-third-party-notices.sh           regenerate both files
#   ./scripts/generate-third-party-notices.sh --check   exit 1 if either is stale
#
# Run it again and commit the result whenever a dependency is added or updated.
# The Test workflow runs --check on every pull request.
#
# The app currently links nothing but Apple's system frameworks, which are part
# of macOS and are not redistributed, so the notices say that no third-party
# library is bundled. The script refuses to write that statement once the
# project gains a Swift package: at that point it has to be extended to read the
# pins from Package.resolved and copy each package's LICENSE (resolving packages
# needs macOS, so the extended script may assume it).
set -euo pipefail

cd "$(dirname "$0")/.."

MODE=write
case "${1:-}" in
  '') ;;
  --check) MODE=check ;;
  *)
    echo "Usage: generate-third-party-notices.sh [--check]" >&2
    exit 1
    ;;
esac

TXT=THIRD-PARTY-NOTICES.txt
SWIFT=Icontuck/ThirdPartyNotices.swift
PBXPROJ=Icontuck.xcodeproj/project.pbxproj

# A package dependency shows up both as a reference in the project file and as a
# Package.resolved next to it; either one means the fixed text below is wrong.
if grep -qE 'XC(Remote|Local)SwiftPackageReference' "${PBXPROJ}" \
  || find Icontuck.xcodeproj -name Package.resolved | grep -q .; then
  echo "Error: the project now has Swift package dependencies." >&2
  echo "  Extend this script to list them (see the comment at the top) before regenerating." >&2
  exit 1
fi

notices() {
  cat <<'TEXT'
THIRD-PARTY NOTICES

Icontuck does not bundle any third-party libraries. It is built only from its
own Swift sources against Apple's system frameworks (AppKit, SwiftUI and
ServiceManagement), which are part of macOS and are not redistributed with the
app, so there are no third-party licenses to reproduce here.

Icontuck itself is released under the MIT License; see LICENSE in
https://github.com/cyberneura/icontuck.

Generated by scripts/generate-third-party-notices.sh; do not edit by hand.
TEXT
}

swift_source() {
  local text
  text=$(notices)
  # The text goes into a raw string literal delimited by #"""; these are the only
  # sequences that could end it or turn into an interpolation.
  case "${text}" in
    *'"""#'* | *'\#'*)
      echo "Error: the notices contain a sequence that breaks the Swift raw string literal." >&2
      exit 1
      ;;
  esac
  cat <<SWIFT
// Generated by scripts/generate-third-party-notices.sh from THIRD-PARTY-NOTICES.txt.
// Do not edit by hand; run the script again instead.

enum ThirdPartyNotices {
    static let text = #"""
${text}
"""#
}
SWIFT
}

# Write next to the destination and move into place, so an interrupted run does
# not leave a half-written file behind.
TMP_TXT=$(mktemp "${TXT}.XXXXXX")
TMP_SWIFT=$(mktemp "${SWIFT}.XXXXXX")
trap 'rm -f "${TMP_TXT}" "${TMP_SWIFT}"' EXIT

notices > "${TMP_TXT}"
swift_source > "${TMP_SWIFT}"

if [ "${MODE}" = check ]; then
  STALE=0
  for pair in "${TXT}:${TMP_TXT}" "${SWIFT}:${TMP_SWIFT}"; do
    file=${pair%%:*}
    fresh=${pair#*:}
    if ! cmp -s "${file}" "${fresh}"; then
      echo "Error: ${file} is out of date. Run ./scripts/generate-third-party-notices.sh and commit the result." >&2
      diff -u "${file}" "${fresh}" >&2 || true
      STALE=1
    fi
  done
  exit "${STALE}"
fi

chmod 644 "${TMP_TXT}" "${TMP_SWIFT}"
mv "${TMP_TXT}" "${TXT}"
mv "${TMP_SWIFT}" "${SWIFT}"
echo "Wrote ${TXT} and ${SWIFT}"
